# On every push this script is executed
on: push
name: Build and deploy GitHub Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/source'
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.14.1
        env:
          # Target branch
          PAGES_BRANCH: master
          # Provide personal access token
          TOKEN: ${{ secrets.TOKEN }}
